title: 俄罗斯方块
imageIconPath: src//main//resources//icon.jpg
size:
  width: 650
  height: 860
mainPanel:
  bounds:
    x: 10
    y: 10
    width: 400
    height: 800
previewPanel:
  bounds:
    x: 450
    y: 10
    width: 160
    height: 160